spring.application.name=24-SB-RestAPI-CRUD

#DB config
spring.datasource.url= jdbc:postgresql://localhost:5432/SB-RestAPI-CRUD
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
